### ISSUE TITLE
Codigo de Barras nao funciona

### ISSUE THREAD

**Issue by ohsolucoes** [CajuCLC/MageBR-Boleto_Bancario_Magento#11]
Ola, implementei o modulo, a linha digitavel esta funcionando.

Porem o codigo de barras nao esta, ele imprimi as barras, mas o leitor do caixa eletronico nao consegue ler.

Alguem sabe me dizer qual o problema?

Desculpe tentei achar a solucao aqui nas outras duvidas, mas nao encontrei.

**Comment by CajuCLC** [comment]
Issue já criado, favor pesquisar:
https://github.com/CajuCLC/MageBR-Boleto_Bancario_Magento/issues/4
