### ISSUE TITLE
Erro no código do boleto / Inicio do Nosso Número

### ISSUE THREAD

**Issue by guztavoalves** [CajuCLC/MageBR-Boleto_Bancario_Magento#12]
Boa tarde,
 
primeiramente parabéns pela iniciativa de criação do módulo para Magento, Boleto Bancário.
Está ajudando muitos desenvolvedores e lojistas. : )
 
Eu estou usando o módulo versão 1.6.6 na versão 1.9 do Magento e achei um erro acredito eu, que seja no módulo, quando gero o boleto Itau ele não adiciona ao número do boleto o código “Inicio do Nosso Número” como na imagem abaixo:

http://prntscr.com/7lasyi

Ele gera o boleto assim:
http://prntscr.com/7latg4

Dae quando o cliente tenta pagar, diz que está inválido ou inexistente.
 
É erro no módulo?
Onde posso encontrar as rotinas que adiciona esse código para que possa gerar o código correto?
 
Obrigado

**Comment by CajuCLC** [comment]
Nosso número são 5 digitos.
Tenho 3 lojas com o Itaú configurado funcionando.
Favor verificar logs de erro do Magento, Apache ou Nginx e colocar aqui.
Favor colocar somente o que for referente ao do boleto.

**Comment by guztavoalves** [comment]
Okay,
veja:

2015-06-26T05:50:14+00:00 ERR (3): Warning: number_format() expects parameter 1 to be double, string given  in /home/vcloud/public_html/app/design/frontend/default/em0072/template/BoletoBancario/banco/itau.phtml on line 79

**Comment by CajuCLC** [comment]
O erro não tem nada com os dígitos.
Se verificar o código irá ver que se refere ao $taxa_boleto que pelo visto não está sendo passado.
Recomendo entrar em contato com seu desenvolvedor para ter certeza que o campo está com algo nele.
Também verificar os requisitos mínimos do number_format e se tiver utilizando o compiler, desativar.
Também utilizar o tema padrão do Magento para testar toda funcionalidade.

**Comment by guztavoalves** [comment]
Certo, mas se você ver nas imagens que mandei na primeira postagem, verá que o valor do "Início do Nosso Número" não está sendo inserido no boleto, quando é gerado o boleto, gera faltando 4 digitos no ultimo bloco de números.

**Comment by CajuCLC** [comment]
Ele precisa gerar o código informado para mostrar alguns campos, ou devido a falha o resto não roda, você precisa verificar com seu programador.
