### ISSUE TITLE
Problema em mostrar boleto mesmo cancelado.

### ISSUE THREAD

**Issue by cesaroito** [CajuCLC/MageBR-Boleto_Bancario_Magento#13]
Parabéns pelo módulo. 
Eu selecionei a opção não mostrar 2ª via se o pedido estiver cancelado, mas ele ainda aparece. Alguma idéia do que pode ser? Eu já limpei o cache, habilitei e desabilitei o modo compilado e ainda nada. Segue dois prints para ajudar.
https://www.dropbox.com/s/gwftao3pdvys1xs/Screen%20Shot%202015-09-04%20at%201.56.48%20PM.png?dl=0
https://www.dropbox.com/s/sfbax5rrclkvce3/Screen%20Shot%202015-09-04%20at%201.56.57%20PM.png?dl=0

Obrigado.

Cesar

**Comment by CajuCLC** [comment]
O recomendado é instalar o módulo também no seu tema.
Qualquer coisa instale o módulo em uma loja nova, sem outros módulos para testar.
A funcionalidade de não mostrar a segunda via está funcionando sem problemas.

**Comment by brunoguirado** [comment]
[Resolvido]

Depois de muitos teste e debugs, encontrei o problema.

O PagSeguro disponibilizou um módulo de "pagamento direto" para magento, de um terceiro (Ideas, dentro de app/core/local), porém, este módulo estava causando o problema, não só para boletos como para todas as outras formas de pagamentos. Modelo removido manualmente, pois não tem instalação pelo Connect, problema resolvido.

Módulo MagentoBR de Boleto, perfeito!
