### ISSUE TITLE
O boleto não abre usando o index.php na frente... como correijo isso?

### ISSUE THREAD

**Issue by adtalbert** [CajuCLC/MageBR-Boleto_Bancario_Magento#14]
Eu estou fazendo o teste no Magento 1.9.2.1
Toda a loja abre com o index.php na frente das pasta... exemplo.... www.loja.com.br/index.php/sales/ ao invés de abrir www.loja.com.br/sales/ ou seja... como faço para as página do boleto abrir usando o endereço correto, com o index.php...

Aqui ele carrega o boleto segunda via:
http://localhost/mag19211/index.php/BoletoBancario/standard/view/order_id/4/

e quando acaba de carregar fica com o endereço assim... (com a página em branco)
http://localhost/mag19211/BoletoBancario/standard/gerar

**Comment by adtalbert** [comment]
Solução:
Abra o arquivo para edição: 
\app\code\community\MageBR\BoletoBancario\Model\Standard.php

Na linha 336 - tire as barras de comentários

// $home_url = Mage::app()->getStore($storeId)->getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK); // Multi Loja.

Deixe assim:

$home_url = Mage::app()->getStore($storeId)->getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK); // Multi Loja.

**Comment by CajuCLC** [comment]
Pelo visto o seu problema era multi-loja.

**Comment by adtalbert** [comment]
O estranho é que eu não utilizo multi-loja, é a instalação padrão do magento, tem apenas uma loja. a não ser que o padrão é reconhecido como multiloja por ter alguns temas como padrão... abraço!

**Comment by CajuCLC** [comment]
Você pode sempre verificar logs do web service rodando para identificar o prolema.
