### ISSUE TITLE
Erro de página ao Enviar 2ª via através da Página de Pedidos no Admin

### ISSUE THREAD

**Issue by adtalbert** [CajuCLC/MageBR-Boleto_Bancario_Magento#15]
Ao clicar no botão Exibir Boleto, o Boleto abre sem problemas.. Mas ao clicar no botão Enviar Boleto por E-mail, Aparece uma página de erro com o nº do log...

Como Resolver?

LOG:
Invalid transactional email code: payment_BoletoBancario_standard_boleto_bancario_email_segunda_via";i:1;s:1268:"#0 C:\wamp\www\loja\app\code\core\Mage\Core\Model\Email\Template.php(494): Mage::exception('Mage_Core', 'Invalid transac...')
#1 C:\wamp\www\loja\app\code\community\MageBR\BoletoBancario\controllers\StandardController.php(309): Mage_Core_Model_Email_Template->sendTransactional('payment_BoletoB...', 'sales', 'cliente@gmai...', 'Cliente de Tal...', Array)
#2 C:\wamp\www\loja\app\code\community\MageBR\BoletoBancario\controllers\StandardController.php(152): MageBR_BoletoBancario_StandardController->_sendNotificationEmail()
#3 C:\wamp\www\loja\app\code\core\Mage\Core\Controller\Varien\Action.php(418): MageBR_BoletoBancario_StandardController->sendmailAction()
#4 C:\wamp\www\loja\app\code\core\Mage\Core\Controller\Varien\Router\Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('sendmail')
#5 C:\wamp\www\loja\app\code\core\Mage\Core\Controller\Varien\Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#6 C:\wamp\www\loja\app\code\core\Mage\Core\Model\App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#7 C:\wamp\www\loja\app\Mage.php(684): Mage_Core_Model_App->run(Array)
#8 C:\wamp\www\loja\index.php(83): Mage::run('', 'store')
#9 {main}";s:3:"url";s:64:"/loja/index.php/BoletoBancario/standard/sendmail/order_id/4/";s:11:"script_name";s:19:"/mag19211/index.php";s:4:"skin";s:7:"default";}

Seria por causa do localhost?

**Comment by CajuCLC** [comment]
Você precisa criar o email transicional. Por favor leia como instalar antes de postar esse tipo de dúvida.

**Comment by adtalbert** [comment]
Já foi criado e feito tudo que esta no manual... por eu tentar é que estou pedindo uma ajuda para quem manja... ou não esta reconhecendo o email ou tem que fazer algum outro passo... instalei em duas loja teste... uma limpa e outra com tema... mais mesmo usando o tema default não faz diferença, já que o problema é no botão no admin... fiz o teste online e no micro em localhost. deu o meus erro... a não ser que eu esteja criando o email tradicional da forma errada... tem como colocar um passa a passo...

eu fiz através do sistema/ email de transação --- carregar Boleto Segunda via... é isso ou tem outra forma? 
Abraço! e obrigado por esta ajudando.

**Comment by adtalbert** [comment]
Fiz todos os procedimentos para o envio o email como vou deixar abaixo:

4 - Entra em Sistema / Email de Transação 
  a - Criar Template
  b - Apresentação - Escolher Novo Pedido
  c - Carregar Template de Email
  d - Achar o tag {{var payment_html}} e colocar em baixo:
{{block type='core/template' area='frontend' template='BoletoBancario/BoletoBancario.phtml' order=$order}}
  e - E caracterizar com o seu jeito... Salvar
  f - Vai em Sistema/Configurações/Vendas/Pedido/ e seleciona o novo template para os novos pedidos
  g - Volte na página de configuração do Boleto Bancário e na 3 parte (Template para o Envio da Segunda Via) escolha o templante que você acabou de criar. e Pronto

Mesmo com tudo certinho não consegui... então baixei novamente os arquivo e substitui os que tinham sido instalado pelo magento connect... e agora esta enviando... algum erro na página dever ter ocorrido e após a substituição dos arquivos, veio a funcionar... mas achem bem colocar a resposta aqui, para saberem que o módulo funciona certinho e que o problema foi resolvido.
