### ISSUE TITLE
Erro de acentuação

### ISSUE THREAD

**Issue by CamaradaDagua** [CajuCLC/MageBR-Boleto_Bancario_Magento#17]
Fiz a instalação pelo Magento Connect da versão 1.6.6 e quando é gerado o boleto aparece com erros de acentuação, conforme abaixo:

![image](https://cloud.githubusercontent.com/assets/9393776/10317776/71b33bd8-6c3c-11e5-885e-5ab0e0bbc7e3.png)

Alguém sabe como posso resolver?

Obrigado.

**Comment by CamaradaDagua** [comment]
Resolvi abrindo o arquivo layout_cep.php e converti em utf-8 pelo notepad++.

**Comment by CajuCLC** [comment]
Ja existe outra issue do mesmo.
