### ISSUE TITLE
Nao gera boletos

### ISSUE THREAD

**Issue by twomidia** [CajuCLC/MageBR-Boleto_Bancario_Magento#20]
Utilizando boleto sicred ou bancoob quando e feita a finalização da compra nao gera o boleto fica uma tela braca

**Comment by CajuCLC** [comment]
Você precisa colocar mais informação, por exemplo logs.

**Comment by Studio7wbe** [comment]
Boa Tarde Eric, conforme  te mandei  por e-mail, estou com problema  para gerar o boleto. 

Esta havendo o mesmo problema no nosso amigo  quando finaliza ou peso para gera a segunda via  ele mostra a tela branca.

**Comment by Studio7wbe** [comment]
Essa informação do CajuCLC: Logs, essa informação é  na tela gera  
 `<?php
class MageBR_BoletoBancario_Block_Standard_Gerar extends Mage_Core_Block_Abstract
 {
    protected function _gerar()
    {

		exit("Oooo");
		
    }
 }`

**Comment by CajuCLC** [comment]
Preciso de logs do apache/nginx.

**Comment by Studio7wbe** [comment]
Conseguir exibir o Boleto Bancário, porem  o Código de barra esta desconfigurada.

**Comment by Studio7wbe** [comment]
Consegui corrigir  era permissão do servidor. 

Att Obrigado

**Comment by Studio7wbe** [comment]
Agora estou com outra duvida que tem  parte em instruções os caracteries especiais não estão funcionando 


UTF-8 

Por favor me  passa as imstrões

**Comment by CajuCLC** [comment]
Fazer buscar no git, já houve essa pergunta.
