### ISSUE TITLE
Não instala na versão do PHP 5.5.22

### ISSUE THREAD

**Issue by geysonx** [CajuCLC/MageBR-Boleto_Bancario_Magento#21]
Prezados amigos da comunidade MageBR, venho vos informar que o modulo de boleto bancário versão 1.6.6 não permite instalação via Magento Connect na versão do "PHP 5.5.22", fora isso se o tentar fazer manualmente ele instala normalmente entretanto não permite que você o habilite pois como citado acima o modulo não suporta esta versão, se houver alguma forma para funcionar com está versão gostaria de ouvir de vocês a maneira correta que eu deveria proceder.

![erro_5 5 22-php](https://cloud.githubusercontent.com/assets/16113864/11525012/9597de02-98ae-11e5-8088-d6300195b70c.png)

**Comment by CajuCLC** [comment]
Isso não é um erro. É devido a permissão.
Eu aumentei a permissão pelo Magento Connect. Tente novamente.

**Comment by geysonx** [comment]
Eric venho agradecer a este suporte e deu tudo certo está tudo funcionando perfeitamente, eu gostaria de saber onde e como fazer uma doação para este serviço! Abraço

Date: Wed, 2 Dec 2015 00:05:39 -0800

**Comment by CajuCLC** [comment]
Que bom que funcionou.
Você pode fazer doação pelo site do boleto:
http://www.boleto.magentobr.com/

Logo na parte onde diz doação.
Abs
