### ISSUE TITLE
Boleto Itau - problema na linha editável

### ISSUE THREAD

**Issue by rafaelferreiraxd** [CajuCLC/MageBR-Boleto_Bancario_Magento#22]
Prezados boa tarde !

Estou com dificuldades para gerar boleto , pois a linha digitável esta saindo incompleta , vocês poderiam me ajudar?

Versão do Magento: 1.6.0.0
att,

Rafael Ferrera
 21 98750-4358
[boleto itau.pdf](https://github.com/CajuCLC/MageBR-Boleto_Bancario_Magento/files/49884/boleto.itau.pdf)

**Comment by CajuCLC** [comment]
Pelo visto você não fez as configurações corretas.

**Comment by rafaelferreiraxd** [comment]
Eric , eu segui o que o manual de instalação pediu . Existe alguma outra configuração? Qual seria?

Att,

Rafael Ferreira

**Comment by CajuCLC** [comment]
Rafael, não disse instalação. Você precisa configurar o módulo após instalar com os dados corretos.
Veja com seu banco quais dados precisa preencher no admin.

**Comment by rafaelferreiraxd** [comment]
Ok , então é erro de configuração ? Eu pensei que fosse erro de instalação.

Grato pela ajuda.

Att,

Rafael Ferreira

**Comment by CajuCLC** [comment]
Exato.

**Comment by Studio7wbe** [comment]
Eric. tudo bem... estou com um problema no boleto que é UTF8 

Demonstrativo 1 : Os Caracteres  especiais não estão funcionando  os acentos estão quebrando. 
Instruções 1
