### ISSUE TITLE
1.6.7 Caixa Econômica Federal‏ Nosso Número - Erro

### ISSUE THREAD

**Issue by geysonx** [CajuCLC/MageBR-Boleto_Bancario_Magento#23]
No campo nosso número eu coloco o mesmo com 17 dígitos mas o mesmo ainda continua com apenas 11 gerando problemas na identificação do boleto, se alguém poder me ajudar, agradeço! =)

**Comment by CajuCLC** [comment]
Por favor coloque os logs.

**Comment by geysonx** [comment]
Ele não gera exceções no log, simplesmente não altera em nada eu escolher a quantidade de dígitos do Nosso Número, simplesmente nada acontece nos logs

**Comment by CajuCLC** [comment]
Estranho, qualquer coisa feita é para gerar logs, seja no web service, magento, etc.
Você já verificou com o gerente de seu banco se os dados colocados estão corretos? 
Você já verificou se a carteira aceita?

**Comment by geysonx** [comment]
sim, eu gero boletos já a um bom tempo e recentemente o problema se encontra no campo nosso número pois o mesmo só produz 11 casas nas quais a caixa exige 17 posições iniciando as 2 com 24. mesmo eu pedindo para que o sistema utilize as 17 posições nada acontece, nem log é gerado nem nada, simplesmente ele continua a imprimir a quantidade do nosso número 11 posições

**Comment by CajuCLC** [comment]
Entendi. Cada campo no módulo é para um banco ou compartilhado por bancos. Você precisa verificar com o banco se os dados estão corretos.
Se você já utilizava e funcionava, recomendo voltar um backup para testes e verificar o que foi alterado que deixou de funcionar.

**Comment by geysonx** [comment]
Não, eu utilizava o programa da própria Caixa para gerar os boletos aqui da empresa, eles eram gerados por SICOB, os dados estão todos corretos o banco já me informou que o problema está no nosso número, que exige 17 posições e o do modulo independente do banco que você escolha ele só utiliza 11 posições no nosso número enviarei as fotos assim que possível para vc compreender oque estou tentando dizer.
