### ISSUE TITLE
Caracteres Especiais

### ISSUE THREAD

**Issue by JakyLindemberg** [CajuCLC/MageBR-Boleto_Bancario_Magento#24]
Boa tarde, utilizo o boleto de vocês em outros sites meu, porém nessa instalação do magento o boleto está aparecendo algumas caracteres estranhas, ja tentei da formas possiveis arrumar isso mas nao consegui, poderiam me auxiliar como arrumar? Deis de já grato!
![boleto](https://cloud.githubusercontent.com/assets/16599260/12181375/ec9e7a54-b568-11e5-941a-aecf888d5bd1.png)

**Comment by CajuCLC** [comment]
Por favor faça busca antes de criar novo issue. Já tem algo:
https://github.com/CajuCLC/MageBR-Boleto_Bancario_Magento/issues/7
