### ISSUE TITLE
Boleto não gera

### ISSUE THREAD

**Issue by Spofff** [CajuCLC/MageBR-Boleto_Bancario_Magento#25]
A forma de pagamento no inicio apareceu só que depois não apareceu mais
Sim, eu uso um tema customizado e já coloquei o código pra temas customizados e tudo mais
![image](https://cloud.githubusercontent.com/assets/16848732/12528710/28ba9448-c17e-11e5-8cfc-a383a2e8478e.png)
![image](https://cloud.githubusercontent.com/assets/16848732/12528717/5266df86-c17e-11e5-98d0-05c80c60df00.png)
OBS: o modulo funciona corretamente o único problema é que não aparece no backend

**Comment by Spofff** [comment]
-- Só acrescentando que eu limpei o cache --

**Comment by Spofff** [comment]
Eric, pode fechar a issue era um probleminha de configuração

Obrigado pelo modúlo 
desculpe o inconveniente.

**Comment by CajuCLC** [comment]
Eu acredito que o problema é que você não colocou o país, correto?
Pode compartilhar como resolveu? Assim você ajuda os outros também.

**Comment by Spofff** [comment]
Simm, eu não coloquei o Pais esse era o problema
na verdade estava selecionado como Estados Unidos e nas configurações gerais só estava configurado para entregar para o Brasil
ai deve ter gerado um conflito eu não sei
