### ISSUE TITLE
Arquivo BoletoBancario.xml como diretório

### ISSUE THREAD

**Issue by apzeiro** [CajuCLC/MageBR-Boleto_Bancario_Magento#26]
Percebi que no diretório app/design/frontend/base/default/layout/
tem um arquivo BoletoBancario.xml que aparece listado como diretório, diferente dos demais arquivos xml do local.

Creio que isso seja algum problema na instalação do módulo.
Estou rodando o módulo na versão 1.6.8

Isso também gera um problema no Connect uma vez que ele não consegue apagar isso.
Para desinstalar, por exemplo precisa pagar isso na mão.

**Comment by apzeiro** [comment]
Para manter um problema sem solução, basta fechar a issue. Nota 10.

**Comment by CajuCLC** [comment]
Fechei por ser de 2016, mas vamos lá.
O arquivo para mim está aparecendo como arquivo e não diretório.
` File: ‘BoletoBancario.xml’
  Size: 524       	Blocks: 8          IO Block: 4096   regular file
Device: 10301h/66305d	Inode: 1970235     Links: 1
Access: (0644/-rw-r--r--)  Uid: (   48/  apache)   Gid: (   48/  apache)
Access: 2017-12-03 05:24:15.889458188 -0200
Modify: 2017-12-03 05:24:15.889458188 -0200
Change: 2017-12-03 05:24:15.893458151 -0200`

Poderia verificar no seu servidor?

**Comment by apzeiro** [comment]
Não possuo mais esse módulo. Desisti dele depois de diversos problemas sem solução. Obrigado pelo retorno.
