### ISSUE TITLE
 load resource: the server responded with a status of 403 (Forbidden)

### ISSUE THREAD

**Issue by Studio7wbe** [CajuCLC/MageBR-Boleto_Bancario_Magento#27]
O que fazer quando  da esse Erro ?

**Comment by CajuCLC** [comment]
Isso é do boleto?
Você já pegou os logs?

**Comment by Studio7wbe** [comment]
Sim isso é do boleto... 
ele não aparece as imagem nem o código de barra sim..  e todas as permissão do servidor já estão liberada.

**Comment by CajuCLC** [comment]
Logs.
