### ISSUE TITLE
Erro de Códificação

### ISSUE THREAD

**Issue by TecSecret** [CajuCLC/MageBR-Boleto_Bancario_Magento#29]
Após realizado a instalação da versão aqui no git o mesmo apresenta erro na codificação das palavras.

_______________________________
**nstru��es de Impress�o

Imprima em impressora jato de tinta (ink jet) ou laser em qualidade normal ou alta (N�o use modo econ�mico).
Utilize folha A4 (210 x 297 mm) ou Carta (216 x 279 mm) e margens m�nimas � esquerda e � direita do formul�rio.
________________________
Erro ocorre em todas as linhas do boleto, usando php 5.6

Abraços

**Comment by CajuCLC** [comment]
Já discutido.
https://github.com/CajuCLC/MageBR-Boleto_Bancario_Magento/issues/7
