### ISSUE TITLE
erro de chartset - palavras com erro 

### ISSUE THREAD

**Issue by albertobraschi** [CajuCLC/MageBR-Boleto_Bancario_Magento#31]
> VocÃª serÃ¡ redirecionado para a pÃ¡gina de impressÃ£o do boleto em 5 segundos. <br />
>                   Se isso nÃ£o ocorrer, clique no botÃ£o "Exibir Boleto".

https://gyazo.com/d87fcd2ff15e924709297b3702fa91e7

E tem no proprio layout do boleto, hora de gerar.

**Comment by GustavoSartori** [comment]
@albertobraschi, alguma novidade? Estou com o mesmo problema aqui.

**Comment by fdaiello** [comment]
Eu rosolvi este problema da seguinte forma.
Localize as pastas:
\app\design\frontend\base\default\template\BoletoBancario\banco\include\
e
\lib\boleto_php\include\
Procure o arquivo de lay_out correspondente ao seu banco. No meu caso: **layout_santander_banespa.php**

Abra o arquivo com o **NotePad**, e de um **Salvar Como**, com o mesmo nome, mas trocando o código de pagina do arquivo para **UTF8**.
Meu servidor é Windows.
Antes todos os acentos viravam um caracter de símbolo.
O procedimento acima resolveu.

**Comment by GustavoSartori** [comment]
@fdaiello Felipe, fiz exatamente isso pouco antes da tua resposta e funcionou!
Valeu pela dica!

**Comment by fdaiello** [comment]
Que bom que esta parte foi resolvida Gustavo.
Boa sorte com seu desenvolvimento.

Abraço,

Felipe Daiello
_______________________________________
felipedaiello@gmail.com
(51) 9109-6510
_______________________________________

Em 26/04/2016 13:32, Gustavo Sartori escreveu:
