### ISSUE TITLE
Errinhos

### ISSUE THREAD

**Issue by vipracing** [CajuCLC/MageBR-Boleto_Bancario_Magento#32]
**1)Estou com problemas de caractéres estranhos no boleto, exemplo:**
Instru��es de Impress�o
Imprima em impressora jato de tinta (ink jet) ou laser em qualidade normal ou alta (N�o use modo econ�mico).
Utilize folha A4 (210 x 297 mm) ou Carta (216 x 279 mm) e margens m�nimas � esquerda e � direita do formul�rio.
Corte na linha indicada. N�o rasure, risque, fure ou dobre a regi�o onde se encontra o c�digo de barras.
Caso n�o apare�a o c�digo de barras no final, clique em F5 para atualizar esta tela.
Caso tenha problemas ao imprimir, copie a sequencia num�rica abaixo e pague no caixa eletr�nico ou no internet banking:

**2) estou com este erro quando mando enviar segunda via pro cliente:**
Invalid transactional email code: payment_BoletoBancario_standard_boleto_bancario_email_segunda_via

Ja revisei o email transicional e ta tudo OK como manda o figurino
podem dar dicas de onde pode ser o problema?

**Comment by emircm** [comment]
vipracing, tive o mesmo problema:

1) Verificando os arquivos layout_*.php todos eles estavam codificados como ISO-8859-1 e deveriam estar UTF-8. Para corrigir:
recode ISO-8859-1..UTF-8 layout_*.php  (se seu ambiente for Linux)
No Windows vc pode usar o Notepad++, menu Encoding --> Encode in UTF-8

Reforçando que você precisa fazer isto nos arquivos das pastas:
app/design/frontend/base/default/template/BoletoBancario/banco/include
lib/boleto_php/include

Boa sorte.
