### ISSUE TITLE
Error 500 na pagina /BoletoBancario/standard/redirect/

### ISSUE THREAD

**Issue by grupouweb** [CajuCLC/MageBR-Boleto_Bancario_Magento#33]
Olá Eric,

Bom dia! Tudo bem? Espero que sim...

Estou testando o seu módulo de boleto com segunda via, mas estou enfrentando um erro 500 que nao consigo depurar...

A URL teste é: http://teste1.uwebdns.com/

O erro 500 acontece no fechamento da compra na URL: http://teste1.uwebdns.com/BoletoBancario/standard/redirect/

Pelo admin eu emito o boleto normalmente e o popup de segunda via tbm funciona normalmente...
Estou rodando na PHP version: 5.4.45
O que pode estar dando de errado?

Desde já agradeço sua atenção...

**Comment by CajuCLC** [comment]
Por favor informe os logs.

**Comment by grupouweb** [comment]
Olá Eric,

Obrigado pelo pronto atendimento...

Segue a linha do Log:
2016-04-26T02:49:44+00:00 ERR (3): Warning: number_format() expects parameter 1 to be double, string given  in /home/teste1/public_html/app/design/frontend/default/theme692/template/BoletoBancario/banco/itau.phtml on line 79

Grato!
