### ISSUE TITLE
Brecha? ou Normal?

### ISSUE THREAD

**Issue by lecosas** [CajuCLC/MageBR-Boleto_Bancario_Magento#37]
Olá Pessoal, 

Primeiramente gostaria de agradecer ao criados do módulo, realmente muito útil e muito bom. Me ajudou muito no desenvolvimento de minha loja.
Bem, não sei muito bem se é uma brecha ou não, pois não tenho tanto conhecimento assim de Magento, mas percebi que path <magento dir>/index.php/BoletoBancario/standard/viewadmin/order_id/<numero do pedido> é possível obter os dados de qualquer cliente, mesmo sem estar logado. O sistema não faz nenhuma verificação para saber se o cliente que está abrindo aquele boleto é ou não o verdadeiro cliente (através de login). 
Se eu enviar este link a um cliente e ele simplesmente mudar o ID do pedido, no final da URL, poderá ter acesso a dados de outro cliente.
Será que existe algo errado na minha configuração ou é uma brecha do módulo?

Agradeço, abs!

**Comment by wdarkin** [comment]
Confirmado! É brecha

**Comment by felipegomesdev** [comment]
Cara, veja se isso te ajuda, para mim pareceu funcionar bem.
Substitua o conteúdo do arquivo: /app/code/community/MageBR/BoletoBancario/controllers/StandardController.php
por este:
https://gist.github.com/felipegomesdev/4dad0eb618f4f2041649f2f9309b30cc

Basicamente agora nos métodos viewAction e viewadminAction, é verificado se o cliente está logado e se a ordem de compra para o qual quer gerar o boleto pertence ao cliente logado. Caso contrário é redirecionado para para página não encontrada.

Fiz alguns testes aqui e me pareceu funcionar bem.
Se quiser testar também, faça os procedimentos em ambiente de testes, se tudo der certo creio eu que o problema fica resolvido.

**Comment by wdarkin** [comment]
@felipegomesdev você sabe se funciona para os links enviados no email da compra? Pois se o cliente gerar o boleto pelo link enviado por email, ele provavelmente não vai estar logado.

**Comment by felipegomesdev** [comment]
@wdarkin atualizei o código do gist, substitua o conteúdo de StandardController.php novamente, limpe o cache.
Para ele redirecionar certo em 'Sistema -> Clientes | Configurações -> Opções de login' é para preciso estar marcado "não", para não redirecionar para o painel do cliente.

***Mas tem um porém, olhando melhor o código, as duas actions(viewAction, viewadminAction) têm o problema, essa minha correção sana o problema somente da viewAction.
Para corrigir a viewadminAction, vejo que o correto seria criar um adminhtml controller para ser possível usar a rotina 'exibir a 2ªvia' no painel administrativo, e com isso fazer os devidos tratamentos.

Se eu aplicar o mesmo tratamento usado na viewAction para a viewadminAction, o admin só consegue gerar a segunda via se o cliente estiver logado na loja. Infelizmente a solução é parcial :(

Esse código testei em uma loja versão 1.9.

**Comment by lecosas** [comment]
Oi @felipegomesdev, não sei se você chegou a arrumar estes probleminhas, mas aparentemente eu atualizei o arquivo que você falou e mesmo sem a configuração Opções de Login estar como 'Não', funcionou tudo normalmente aqui. Mesmo a impressão da 2a. Via pelo painel administrativo.

Você chegou a alterar algo depois de seu último post?

**Comment by felipegomesdev** [comment]
@lecosas  não alterei mais nada no arquivo. Eu achei que seria possível consertar as duas actions no mesmo arquivo, mas somente a 'viewAction' ficou ok, ainda é possível, ver os dados de outros IDs na 'viewAdminAction'. Para consertar isso plenamente, imagino eu que é preciso usar outra abordagem. Daqui mais uns dias volto a mexer no módulo em uma loja que estou desenvolvendo e se eu resolver o problema submeto uma PR para apreciação dos colaboradores.

**Comment by lecosas** [comment]
Legal @felipegomesdev . Forte abraço.

**Comment by lecosas** [comment]
@felipegomesdev estava fazendo alguns testes aqui, e acho que a ideia que o wdarkin deu de criar o link com uma hash é possível de fazer? pois acho que ficou bem mais complicado agora para o cliente imprimir o boleto (caso ele queira ver o boleto alguns dias depois da compra), pois ele tem que logar para vê-lo.
