### ISSUE TITLE
PHP 5.6.22

### ISSUE THREAD

**Issue by brunoguirado** [CajuCLC/MageBR-Boleto_Bancario_Magento#38]
Alguma previsão para rodar no 5.6.22?

Tive que mudar um cliente de servidor e a versão do PHP não consigo mudar pra 5.6.17

CONNECT ERROR: Package community/MageBR_BoletoBancario 1.6.8: requires PHP version >= 5.3.0 and <= 5.6.17 current is: 5.6.22

**Comment by CajuCLC** [comment]
Ainda não foi testado.
Att.
