### ISSUE TITLE
bugs logo do banco, sem acentuação, e codigo de barra apagado.

### ISSUE THREAD

**Issue by aocon** [CajuCLC/MageBR-Boleto_Bancario_Magento#4]
Não aparece o logo do banco do brasil, nao eceita assentuação e o codigo de barras sai apagado quando é gerado o boleto..
ja dei uma mechida.. coloquei layout do modulo para dentro do meu tema, mas nao adiantou nada..

Sera que alguem por ai ja passou por isso ?

**Comment by Studio7wbe** [comment]
Desculpa  mas conforme  o que vc  me pediu para pesquisar  o meu erro  é diferente.. 

Os único ponto que  não esta aceitando  as acentuação são: 

Demonstrativo 1 - 
Instruções 1 - 

Quando informamos  as informações em forma de pagamento Dentro do Admin Magento. 

Por favor como devo proceguir, pois no meu caso não é permissão pois ja liberei praticamento tudo do servidor.

**Comment by CajuCLC** [comment]
Você pode verificar nos arquivos.
Eles estão na pasta: https://github.com/CajuCLC/MageBR-Boleto_Bancario_Magento/tree/master/lib/boleto_php
