### ISSUE TITLE
Problema de Encode

### ISSUE THREAD

**Issue by renatolovato** [CajuCLC/MageBR-Boleto_Bancario_Magento#7]
Olá, não sei o que pode estar ocorrendo, mas, ao implementar o Boleto Bancário Magento todas as páginas do mesmo ficam com problema de charset.

Há alguma coisa que eu possa fazer para arrumar este problema?

Já aconteceu algumas vezes isso comigo com arquivos que são gerados no Windows e abro na minha máquina que está com Mac OS, talvez seja alguma problema neste sentido?

**Comment by CajuCLC** [comment]
Renato, você pode verificar no seu PHP se está usando o charset correto.
Recomendo entrar em contato com sua empresa de hospedagem.
Att.

**Comment by renatolovato** [comment]
Ol CajuCLC, na verdade eu mesmo administro o servidor, utilizo o padrão UTF-8, mas, o único plugin que eu tive este problema foi este, mas, dei um jeito um tanto quando "Extreme Go Horse", alterei o encode dos arquivos do banco que eu estou utilizando para UTF-8 (converti) e o problema se resolveu.

Obrigado.

**Comment by CajuCLC** [comment]
(y)

**Comment by JakyLindemberg** [comment]
Ja estou utilizando utf-8 no banco de dados e nao resolveu o problema

**Comment by CajuCLC** [comment]
Por favor leia o issue. Não é no banco de dados.
