### ISSUE TITLE
Boleto BB não emite nota

### ISSUE THREAD

**Issue by brunowd** [CajuCLC/MageBR-Boleto_Bancario_Magento#8]
Olá, preciso de uma ajuda.
Eu baixei e instalei o módulo de boleto bancário, ele até chegou a emitir mas sem o código de barras e alguns caracteres errados, tem como me ajudar? Segue em anexo o primeiro boleto que emite lá!
Obrigado.
--------------------------------------
Os caracteres especiais já solucionei trocando o arquivo layout_bb para UTF-8 e resolveu.
Só falta ver o porque de não estar emitindo a nota :+1:

**Comment by CajuCLC** [comment]
Verifique o código HTML, pode estar puxando as imagens do local errado.

**Comment by brunowd** [comment]
Pra isso tenho que ativar o módulo e verificar no inspetor?

**Comment by CajuCLC** [comment]
Sim.
